### ISSUE TITLE
Changing the logLevel centrally

### ISSUE THREAD

**Issue by drallgood** [sushichop/Puppy#73]
For some reason I have to create my own copy of `PuppyLogHandler` so I can enable/disable debug logging centrally.
Whenever I try to use `PuppyLogHandler` (a single instance for all Loggers) and then set the logLevel, it's not taken into account.
However, If I try my cloned class, it works.
Pretty strange.

The only issue is that I can't use the `puppy.logMessage(...)` method because it's not public.

Is it possible to expose it? Or alternatively allow the individual methods (error, trace,...) to also pass swiftLogInfo?
  

Here's how I'm using it:
```
private static var handler: PuppyLogHandler?

private static func initLogging() {
// ... (more code)
        let puppy = Puppy(loggers: loggers)
        handler = PuppyLogHandler(label: "\(LOGGING_PREFIX).PuppyLogHandler", puppy: puppy)

        // Set the default logging level.
        #if DEBUG
        handler?.logLevel = .debug
        #else
        handler?.logLevel = .info
        #endif

        LoggingSystem.bootstrap { _ in
            return handler!
        }
    }
    
    static func enableDebugLogging(_ enableDebugLogging: Bool) {
        handler?.logLevel = enableDebugLogging ? .debug : .info
    }
```

**Comment by sushichop** [comment]
Thanks for creating this issue. and sorry for the late response.
I may not understand your issue correctly, though...

First of all, not `PupplyLogHandler` but the `Puppy` instance() has the ability to aggregate each logger.
Each logger (e.g. FileLogger) is supposed to be used as an addition to the Puppy instance.
See the `basic example` in [README](https://github.com/sushichop/Puppy/blob/main/README.md).

`PuppyLogHandler` is used only for the connection between various apple/swift-log backends(including `Puppy` itself) and the Puppy instance.
See the `Use with apple/swift-log` example in [README](https://github.com/sushichop/Puppy/blob/main/README.md).

**Comment by sushichop** [comment]
Thanks for your explanation.
Now I feel I understand what you say, but I originally implemented the above with that intention because it is optional to use swift-log with Puppy. 
__I implemented so that it works without swift-log.__ (In addition, it is also intended that the log level can be set for each log source (ConsoleLogger, FileLogger, etc.).)

On the other hand, if you want to set up a centralized log filter when using swift-log, it is intended to be set up the way you have already described.

> private static var handler: PuppyLogHandler?
> 
> private static func initLogging() {
> // ... (more code)
>         let puppy = Puppy(loggers: loggers)
>         handler = PuppyLogHandler(label: "\(LOGGING_PREFIX).PuppyLogHandler", puppy: puppy)
> 
>         // Set the default logging level.
>         #if DEBUG
>         handler?.logLevel = .debug
>         #else
>         handler?.logLevel = .info
>         #endif
> 
>         LoggingSystem.bootstrap { _ in
>             return handler!
>         }
>     }
>     
>     static func enableDebugLogging(_ enableDebugLogging: Bool) {
>         handler?.logLevel = enableDebugLogging ? .debug : .info
>     }

The example is also here.
https://github.com/sushichop/Puppy/blob/672b23f19d381039523a235b41ea5625a8ed8248/Tests/PuppyTests/PuppyLogHandlerTests.swift#L24-L36

That's why, default log level for ConsoleLogger and FileLogger is set to .trace.
As a result, this helps you omit set the each log level when you use swift-log with Puppy.

This may be confusing, but the emphasis is on being able to filter the log level for each log source and the case when swift-log is not used...

In any case, I might set the default log level of PuppyLogHandler to .trace for ease of use when debugging.

Thanks.

**Comment by drallgood** [comment]
Hence why i asked whether you could expose the puppy.logMessage(...) method. Or alternatively allow the individual methods (error, trace,...) to also pass swiftLogInfo. 

This way I can have my custom implementation and don't have to copy stuff 😊

**Comment by sushichop** [comment]
Thanks. 
I know, but it depends on the modification😅

In order to gradually support Swift 6 for the future, I have already made `Puppy` and `PuppyLogHandler` to be struct (not class) and conformable to Sendable. 
So exposing  `puppy.logMessage(...)` is welcome as long as you can keep these conforming to Sendable.

Could you please send me a PR to do this?
Because, TBH, I'm not sure if we can do this soon or not...

Thanks.

**Comment by drallgood** [comment]
Done.. but anyway turns out I made a mistake somewhere and it even works without this change.
However, I thought it might anyway be helpful to have access to this method

**Comment by sushichop** [comment]
@drallgood 
Thanks. I may have confused you a bit, but there is no problem changing it to public for now.

Could you send me a pull request?
I'm glad to merge it🙂

**Comment by drallgood** [comment]
@sushichop DOH
I thought I had opened one... I did.. just in my own fork instead of in this project 🤣
